name: Weekly Geospatial Stock Snapshot

on:
  schedule:
    # Run every Friday at 8 PM EST (1 AM UTC Saturday, since EST is UTC-5)
    - cron: '0 1 * * 6'
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write

jobs:
  capture-snapshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Capture weekly snapshot
        run: |
          python scripts/snapshot.py
      
      - name: Upload Parquet artifact
        uses: actions/upload-artifact@v4
        with:
          name: weekly-snapshot-${{ github.run_number }}
          path: snapshots/*.parquet
          retention-days: 90
